In [1]:
import torch
import torch.nn as nn

# Create a MaxPool2d layer with return_indices=True
pool = nn.MaxPool2d(kernel_size=2, stride=2, return_indices=True)

# Sample input
input = torch.tensor([[
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]], dtype=torch.float)

# Forward pass
pooled_output, indices = pool(input)

print("Original input:")
print(input[0])
# Output:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]
#  [13 14 15 16]]

print("\nPooled output (output[0]):")
print(pooled_output[0])
# Output:
# [[ 6  8]
#  [14 16]]

print("\nIndices (output[1]):")
print(indices[0])
# Output (positions of max values):
# [[5 7]
#  [13 15]]

Original input:
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])

Pooled output (output[0]):
tensor([[ 6.,  8.],
        [14., 16.]])

Indices (output[1]):
tensor([[ 5,  7],
        [13, 15]])


In [2]:
from functools import partial

# Regular function with multiple parameters
def greet(name, greeting):
    return f"{greeting}, {name}!"

# Creating a new function with 'greeting' pre-filled
say_hello = partial(greet, greeting="Hello")
say_hi = partial(greet, greeting="Hi")

# Now we can call these with just the name
print(say_hello("Alice"))  # Output: "Hello, Alice!"
print(say_hi("Bob"))      # Output: "Hi, Bob!"

Hello, Alice!
Hi, Bob!


: 